# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - bdsagroup12girlschirpremotedb #ændr navn

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: Chirp

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ./Chirp/Chirp.Razor
        
      - name: Build
        run: dotnet build ./Chirp/Chirp.Razor --configuration Release
        
      - name: Test
        run: dotnet test ./Chirp/Chirp.Razor --no-build --verbosity normal
        
      - name: Publish
        run: dotnet publish ./Chirp/Chirp.Razor -c Release --property:PublishDir='publish'
        
      - name: Zip
        run: zip -r myApp.zip ./publish
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: razor-app
          path: myApp.zip
  
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
      
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: razor-page
          path: ./artifacts
      
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bdsagroup12chirpremotedb2' #ændr navn her også
          publish-profile: ${{ secrets.AZURE_WEB_PUBLISH_PROFILE_2 }} #skal måske også ændres
          package: "./artifacts/myApp.zip"
          type: ZIP