name: Publish

on:
  workflow_dispatch: 
    
  push:
    tags:
      - 'v.*'
  release:
    types: [published]


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
  
  release_MacOS:
    name: Release MacOS
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Release
        run: dotnet publish -c Release -r osx-x64 -p:PublishSingleFile=true -o ./publish/osx-64
      - name: ZIP
        run: zip -r osx.zip ./publish/osx-64
    

  publish:
    name: Publish
    needs: release MacOS
    uses: softprops/action-gh-release@v2
    with:
      files: |
          osx.zip
       
    
          
            
            

