name: Publish

on:
  workflow_dispatch: 
    
  push:
    tags:
      - 'v.*'
  release:
    types: [published]


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
  
  release_MacOS:
    name: Release MacOS
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Release
        run: dotnet publish -c Release -r osx-x64 -p:PublishSingleFile=true -o ./publish/osx-x64
      - name: ZIP
        run: zip -r osx.zip ./publish/osx-64
        
  release_windows:
    name: Release Windows
    needs: build
    runs-on: ubuntu-latest
  
    steps:
      - name: Release
        run: dotnet publish -c Release -r win-x64 -p:PublishSingeFile=true -o ./publish/win-x64
      - name: ZIP
        run: zip -r win.zip ./publish/win-x64
  
  release_Linux:
    name: Release Linux
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Release
        run: dotnet publish -c Release -r linux-x64 -p:PublishSingleFile:true -o ./publish/linux-x64
      - name: ZIP
        run: zip -r linux.zip ./publish/linux-x64

  publish:
    name: Publish
    needs: [release_MacOS, release_Windows, release_Linux]
    runs-on: ubuntu-latest
    
    steps:
    - name: release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          osx.zip
          win.zip
          linux.zip
          
         
    
          
            
            

